### ISSUE TITLE
Alexander downloads and runs new code from Dad

### ISSUE THREAD

**Issue by billhiggins** [ayhiggins/experiments#2]
In issue #1, you set up a Python development environment, created a “hello, world” program, and shared it with me by pushing your [commit containing your new files](https://github.com/ayhiggins/experiments/commit/ab05d4302ba1c0a10beaf7ea8d67c884d74332b5) it to this GItHub repo.

In this example, I’ll push up a new program and your assignment is to figure out how to download it correctly and run it. You’re done when you do two things, which we’ll refer to as the “acceptance criteria”:

- [x] You can show me the program successfully running in your VSCode environment
- [x] You can explain the program line by line, in your own words (it has good documentation)

I’ll close by documenting key concepts at the end of this issue.

A hint: Almost everything you need to know in order to complete this issue is documented in [the final comment of issue 1](https://github.com/ayhiggins/experiments/issues/1#issuecomment-640537309). You’ll have to figure out the git command to download my change, but I think you should be able to figure it out—it’s the opposite of the command used to upload your change.

**Comment by billhiggins** [comment]
I’ve pushed [my commit](https://github.com/ayhiggins/experiments/commit/8c49fb2cc29cfa28c963f887661e7c1d74c1a264) containing the simple adder program.

You may recall we created this program together on Christmas Day, 2019. I updated it just a bit to work with Python 3 and also to have more and clearer comments (the lines that begin with `#`).

![Alexander writing his first program on Christmas Day, 2019](https://user-images.githubusercontent.com/4076963/84027431-f6261e00-a95c-11ea-9ed0-3820ce2f1091.jpg)

**Comment by docwhat** [comment]
Hello!  This is @docwhat -- I helped out your dad (@billhiggins ) today some.  Feel free to ask questions and I'll do me best to get you an answer.

**Comment by billhiggins** [comment]
What we learned.

**Catching up with the team’s work**

(Note: From here on out, I’ll refer to us working in this collaborative mode as “the team” since this terminology is what you would use if you were on a real software engineering team.)

In issue #1, you created a simple `Hello, world!` program, created a local commit, then shared your change with the team by pushing the commit up to GitHub.

In this issue, we did the opposite: a team member (me) had pushed their own commit and you caught up with the team with the following commands:

```
# Get latest change history from GitHub; note VSCode had already done this for
# you, so you didn’t actually run this, but going forward, you should
git fetch

# See if there are any differences between GitHub and your coputer
git status

# Download all changes from GitHub
git pull
```

**A fragile program**

When you were running the `adder` program, I asked you to enter a non-integer to see what happens; when you did, you saw the following behavior:

```
Bills-MacBook-Pro:experiments billh$ python adder.py
Enter an integer:
hello
Traceback (most recent call last):
  File "adder.py", line 13, in <module>
    num3 = int(user_input)
ValueError: invalid literal for int() with base 10: 'hello'
```

A good program guards against bad user input and provides helpful feedback to help users succeed. In issue #4, we’ll make our program more robust so that it doesn’t fail if a user provides bad input.
